### ISSUE TITLE
[FE] Ability to set dash distance & dash length

### ISSUE THREAD

**Issue by KaustubhPatange** [edgar-zigis/GaugeProgressView#3]
Would be great if you add this?

**Comment by edgar-zigis** [comment]
Dash length can be already set by using `gpv_innerArcThickness` parameter.
I can add dash distance too if you wish so.

**Comment by KaustubhPatange** [comment]
Yeah, dash distance would be good.

**Comment by edgar-zigis** [comment]
Done! 
You can edit both dash thickness & distance by adding these xml params
```
app:gpv_innerArcDashDistance="8dp"
app:gpv_innerArcDashThickness="2dp"
```
or just simply setting required values from your code.
